// Session query layer — Phase 1 Auth (B01).
// Runtime sqlx queries (no DATABASE_URL at compile time).
//
// A session row IS the token: `sessions.id` is a UUID v4 handed to the caller and
// held in the OS keychain. Validity is a pure DB question — `expires_at > now` —
// so a restart can restore a session without the user re-authenticating.
//
// All timestamps are SQLite `datetime('now')` strings ('YYYY-MM-DD HH:MM:SS', UTC).
// That format sorts lexicographically, so `expires_at > datetime('now')` is a
// correct comparison without any parsing.

use sqlx::SqlitePool;

/// How long a session stays valid after creation or refresh.
/// specs/auth-rbac.md: "expires_at DATETIME NOT NULL, -- 8 hours from creation"
pub const SESSION_TTL_HOURS: i64 = 8;

#[derive(Debug, sqlx::FromRow)]
pub struct SessionRow {
    pub id:               String,
    pub user_id:          String,
    pub expires_at:       String,
    pub last_activity_at: String,
    pub created_at:       String,
    pub updated_at:       String,
}

/// A session joined to its user — what `get_session` needs in one round trip.
#[derive(Debug, sqlx::FromRow)]
pub struct SessionWithUser {
    pub session_id: String,
    pub expires_at: String,
    pub user_id:    String,
    pub name:       String,
    pub email:      String,
    pub role:       String,
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/// Create a session valid for `SESSION_TTL_HOURS`. Returns the stored row.
/// `id` is generated by the caller (uuid v4) so the token never round-trips.
pub async fn create(pool: &SqlitePool, id: &str, user_id: &str) -> anyhow::Result<SessionRow> {
    let ttl = format!("+{SESSION_TTL_HOURS} hours");

    sqlx::query(
        "INSERT INTO sessions (id, user_id, expires_at)
         VALUES (?, ?, datetime('now', ?))",
    )
    .bind(id)
    .bind(user_id)
    .bind(&ttl)
    .execute(pool)
    .await?;

    get(pool, id)
        .await?
        .ok_or_else(|| anyhow::anyhow!("session not found after insert"))
}

/// Fetch a session regardless of expiry.
pub async fn get(pool: &SqlitePool, id: &str) -> anyhow::Result<Option<SessionRow>> {
    let row = sqlx::query_as::<_, SessionRow>(
        "SELECT id, user_id, expires_at, last_activity_at, created_at, updated_at
         FROM sessions WHERE id = ?",
    )
    .bind(id)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// Fetch a session and its user, but only if the session is unexpired and the
/// user is still active. This is the single validity gate used by get_session.
pub async fn get_valid_with_user(
    pool: &SqlitePool,
    id: &str,
) -> anyhow::Result<Option<SessionWithUser>> {
    let row = sqlx::query_as::<_, SessionWithUser>(
        "SELECT s.id AS session_id, s.expires_at AS expires_at,
                u.id AS user_id, u.name AS name, u.email AS email, u.role AS role
         FROM sessions s
         JOIN users u ON u.id = s.user_id
         WHERE s.id = ?
           AND s.expires_at > datetime('now')
           AND u.is_active = 1",
    )
    .bind(id)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// Stamp last_activity_at without changing expiry. Cheap; safe to call often.
pub async fn touch(pool: &SqlitePool, id: &str) -> anyhow::Result<()> {
    sqlx::query(
        "UPDATE sessions
         SET last_activity_at = datetime('now'), updated_at = datetime('now')
         WHERE id = ?",
    )
    .bind(id)
    .execute(pool)
    .await?;
    Ok(())
}

/// Extend expiry to SESSION_TTL_HOURS from now. Only extends a session that is
/// still valid — an expired session can never be revived, it must be re-created
/// by logging in again.
pub async fn refresh(pool: &SqlitePool, id: &str) -> anyhow::Result<Option<SessionRow>> {
    let ttl = format!("+{SESSION_TTL_HOURS} hours");

    let result = sqlx::query(
        "UPDATE sessions
         SET expires_at       = datetime('now', ?),
             last_activity_at = datetime('now'),
             updated_at       = datetime('now')
         WHERE id = ? AND expires_at > datetime('now')",
    )
    .bind(&ttl)
    .bind(id)
    .execute(pool)
    .await?;

    if result.rows_affected() == 0 {
        return Ok(None);
    }
    get(pool, id).await
}

/// Delete one session (logout).
pub async fn delete(pool: &SqlitePool, id: &str) -> anyhow::Result<()> {
    sqlx::query("DELETE FROM sessions WHERE id = ?")
        .bind(id)
        .execute(pool)
        .await?;
    Ok(())
}

/// Delete every session for a user (password change, deactivation).
pub async fn delete_for_user(pool: &SqlitePool, user_id: &str) -> anyhow::Result<u64> {
    let result = sqlx::query("DELETE FROM sessions WHERE user_id = ?")
        .bind(user_id)
        .execute(pool)
        .await?;
    Ok(result.rows_affected())
}

/// Housekeeping — drop expired rows. Called at startup.
pub async fn delete_expired(pool: &SqlitePool) -> anyhow::Result<u64> {
    let result = sqlx::query("DELETE FROM sessions WHERE expires_at <= datetime('now')")
        .execute(pool)
        .await?;
    Ok(result.rows_affected())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    async fn test_pool() -> SqlitePool {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();

        sqlx::query(
            "CREATE TABLE users (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                role TEXT NOT NULL DEFAULT 'Associate',
                password_hash TEXT NOT NULL,
                is_active INTEGER NOT NULL DEFAULT 1,
                last_login_at DATETIME,
                created_at DATETIME NOT NULL DEFAULT (datetime('now')),
                updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
            )",
        )
        .execute(&pool)
        .await
        .unwrap();

        sqlx::query(
            "CREATE TABLE sessions (
                id TEXT PRIMARY KEY,
                user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at DATETIME NOT NULL,
                last_activity_at DATETIME NOT NULL DEFAULT (datetime('now')),
                created_at DATETIME NOT NULL DEFAULT (datetime('now')),
                updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
            )",
        )
        .execute(&pool)
        .await
        .unwrap();

        sqlx::query(
            "INSERT INTO users (id, name, email, role, password_hash)
             VALUES ('user-slm', 'Sree Lakshmi Menon', 'slm@persist.in', 'Partner', 'x')",
        )
        .execute(&pool)
        .await
        .unwrap();

        pool
    }

    /// Insert a session with an explicit expiry offset, bypassing create().
    async fn insert_with_expiry(pool: &SqlitePool, id: &str, modifier: &str) {
        sqlx::query(
            "INSERT INTO sessions (id, user_id, expires_at)
             VALUES (?, 'user-slm', datetime('now', ?))",
        )
        .bind(id)
        .bind(modifier)
        .execute(pool)
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn create_returns_valid_session_with_user() {
        let pool = test_pool().await;
        let row = create(&pool, "sess-1", "user-slm").await.unwrap();
        assert_eq!(row.user_id, "user-slm");

        let joined = get_valid_with_user(&pool, "sess-1").await.unwrap();
        assert!(joined.is_some());
        let joined = joined.unwrap();
        assert_eq!(joined.name, "Sree Lakshmi Menon");
        assert_eq!(joined.role, "Partner");
        assert_eq!(joined.email, "slm@persist.in");
    }

    #[tokio::test]
    async fn expired_session_is_not_valid() {
        let pool = test_pool().await;
        insert_with_expiry(&pool, "sess-old", "-1 hours").await;

        // The row exists...
        assert!(get(&pool, "sess-old").await.unwrap().is_some());
        // ...but it does not validate.
        assert!(get_valid_with_user(&pool, "sess-old").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn inactive_user_invalidates_session() {
        let pool = test_pool().await;
        create(&pool, "sess-2", "user-slm").await.unwrap();
        assert!(get_valid_with_user(&pool, "sess-2").await.unwrap().is_some());

        sqlx::query("UPDATE users SET is_active = 0 WHERE id = 'user-slm'")
            .execute(&pool)
            .await
            .unwrap();

        assert!(get_valid_with_user(&pool, "sess-2").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn refresh_extends_expiry_of_valid_session() {
        let pool = test_pool().await;
        // Expires in 1 hour — refresh should push it out to ~8 hours.
        insert_with_expiry(&pool, "sess-3", "+1 hours").await;
        let before = get(&pool, "sess-3").await.unwrap().unwrap().expires_at;

        let after = refresh(&pool, "sess-3").await.unwrap();
        assert!(after.is_some(), "valid session should refresh");
        assert!(
            after.unwrap().expires_at > before,
            "refresh must push expires_at later"
        );
    }

    #[tokio::test]
    async fn refresh_refuses_expired_session() {
        let pool = test_pool().await;
        insert_with_expiry(&pool, "sess-dead", "-5 minutes").await;

        // An expired session must not be revivable — login is the only way back.
        assert!(refresh(&pool, "sess-dead").await.unwrap().is_none());
        assert!(get_valid_with_user(&pool, "sess-dead").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn delete_removes_session() {
        let pool = test_pool().await;
        create(&pool, "sess-4", "user-slm").await.unwrap();
        delete(&pool, "sess-4").await.unwrap();
        assert!(get(&pool, "sess-4").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn delete_expired_only_removes_stale_rows() {
        let pool = test_pool().await;
        insert_with_expiry(&pool, "keep", "+2 hours").await;
        insert_with_expiry(&pool, "drop-1", "-1 hours").await;
        insert_with_expiry(&pool, "drop-2", "-30 minutes").await;

        let removed = delete_expired(&pool).await.unwrap();
        assert_eq!(removed, 2);
        assert!(get(&pool, "keep").await.unwrap().is_some());
        assert!(get(&pool, "drop-1").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn delete_for_user_clears_all_their_sessions() {
        let pool = test_pool().await;
        create(&pool, "s-a", "user-slm").await.unwrap();
        create(&pool, "s-b", "user-slm").await.unwrap();

        let removed = delete_for_user(&pool, "user-slm").await.unwrap();
        assert_eq!(removed, 2);
        assert!(get(&pool, "s-a").await.unwrap().is_none());
    }

    #[tokio::test]
    async fn touch_updates_activity_without_extending_expiry() {
        let pool = test_pool().await;
        insert_with_expiry(&pool, "sess-5", "+3 hours").await;
        let before = get(&pool, "sess-5").await.unwrap().unwrap();

        touch(&pool, "sess-5").await.unwrap();
        let after = get(&pool, "sess-5").await.unwrap().unwrap();

        assert_eq!(
            before.expires_at, after.expires_at,
            "touch must not change expiry — only refresh does"
        );
    }
}
